using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Reflection;
using CommunityToolkit.Mvvm.ComponentModel;
using FluentValidation;
using Model.ViewModels;

namespace ViewModel.Commons.Fields;

/// <summary>
/// FieldViewModel for managing collections of ViewModels.
/// Renders as an HTML table in the UI via CollectionFieldView.
///
/// Key Features:
/// - ObservableCollection with change notification
/// - Lazy loading via Query function
/// - Add/Update/Delete permissions
/// - Column definitions auto-generated from IFieldViewModel properties
/// </summary>
/// <typeparam name="T">The ViewModel type for items in the collection.</typeparam>
public partial class CollectionFieldViewModel<T> : ObservableObject, ICollectionFieldViewModel
    where T : class
{
    private ObservableCollection<T>? _collection;
    private T? _selectedItem;
    private readonly Func<IEnumerable<T>>? _query;
    private bool _isInitialized;
    private List<PropertyInfo>? _columnProperties;

    // UI Metadata
    private string? _label;
    private string? _hint;
    private bool _readOnly;
    private string? _error;
    private string? _warning;
    private string? _columnWidth;
    private bool _hiddenInColumn;

    // Permission flags
    private bool _allowAdd = true;
    private bool _allowUpdate = true;
    private bool _allowDelete = true;

    // Commands
    private CommandViewModel? _addCommand;
    private CommandViewModel<T>? _deleteCommand;
    private CommandViewModel? _refreshCommand;

    public CollectionFieldViewModel(
        object? parent = null,
        Func<IEnumerable<T>>? query = null)
    {
        Parent = parent;
        _query = query;
        BuildColumnProperties();
    }

    public object? Parent { get; }

    #region Collection Property

    /// <summary>
    /// The observable collection of ViewModels.
    /// Lazy-loaded from Query on first access.
    /// </summary>
    public ObservableCollection<T> Collection
    {
        get
        {
            if (!_isInitialized && _query != null)
            {
                _collection = new ObservableCollection<T>(_query());
                _collection.CollectionChanged += OnCollectionChanged;
                _isInitialized = true;
            }
            return _collection ??= new ObservableCollection<T>();
        }
    }

    /// <summary>
    /// Number of items in the collection.
    /// </summary>
    public int Count => Collection.Count;

    /// <summary>
    /// Currently selected item.
    /// </summary>
    public T? SelectedItem
    {
        get => _selectedItem;
        set => SetProperty(ref _selectedItem, value);
    }

    #endregion

    #region UI Metadata

    public string? Label
    {
        get => _label;
        set => SetProperty(ref _label, value);
    }

    public string? Hint
    {
        get => _hint;
        set => SetProperty(ref _hint, value);
    }

    public bool ReadOnly
    {
        get => _readOnly;
        set => SetProperty(ref _readOnly, value);
    }

    public string? Error
    {
        get => _error;
        private set => SetProperty(ref _error, value);
    }

    public string? Warning
    {
        get => _warning;
        private set => SetProperty(ref _warning, value);
    }

    public string? ColumnWidth
    {
        get => _columnWidth;
        set => SetProperty(ref _columnWidth, value);
    }

    public bool HiddenInColumn
    {
        get => _hiddenInColumn;
        set => SetProperty(ref _hiddenInColumn, value);
    }

    public bool HasSetValueFunction => false;

    #endregion

    #region Permissions

    public bool AllowAdd
    {
        get => _allowAdd && !ReadOnly;
        set => SetProperty(ref _allowAdd, value);
    }

    public bool AllowUpdate
    {
        get => _allowUpdate && !ReadOnly;
        set => SetProperty(ref _allowUpdate, value);
    }

    public bool AllowDelete
    {
        get => _allowDelete && !ReadOnly;
        set => SetProperty(ref _allowDelete, value);
    }

    #endregion

    #region Column Discovery

    /// <summary>
    /// List of IFieldViewModel properties visible as columns.
    /// Auto-generated by reflection on T.
    /// </summary>
    public IReadOnlyList<IFieldViewModel> ColumnFields
    {
        get
        {
            if (Collection.Count == 0 || _columnProperties == null)
                return Array.Empty<IFieldViewModel>();

            var firstItem = Collection.First();
            return _columnProperties
                .Select(p => p.GetValue(firstItem) as IFieldViewModel)
                .Where(f => f != null && !f.HiddenInColumn)
                .ToList()!;
        }
    }

    /// <summary>
    /// Property infos for column rendering (used by view).
    /// </summary>
    public IReadOnlyList<PropertyInfo> ColumnProperties => _columnProperties ?? new List<PropertyInfo>();

    private void BuildColumnProperties()
    {
        _columnProperties = typeof(T)
            .GetProperties()
            .Where(p => typeof(IFieldViewModel).IsAssignableFrom(p.PropertyType))
            .ToList();
    }

    #endregion

    #region CRUD Delegates

    /// <summary>
    /// Function to create a new item.
    /// </summary>
    public Func<T>? CreateItem { get; set; }

    /// <summary>
    /// Callback after an item is added (e.g., add Model to DbSet).
    /// </summary>
    public Action<T>? OnItemAdded { get; set; }

    /// <summary>
    /// Callback when an item is deleted (e.g., delete entity from UnitOfWork).
    /// </summary>
    public Action<T>? OnItemDeleted { get; set; }

    #endregion

    #region Commands

    /// <summary>
    /// Command to add a new item to the collection.
    /// </summary>
    public CommandViewModel AddCommand => _addCommand ??= new CommandViewModel(
        parent: this,
        text: "Add",
        hint: "Add a new item",
        execute: Add,
        canExecute: () => AllowAdd && CreateItem != null,
        style: CommandStyle.Success
    );

    /// <summary>
    /// Command to delete an item from the collection.
    /// </summary>
    public CommandViewModel<T> DeleteCommand => _deleteCommand ??= new CommandViewModel<T>(
        parent: this,
        text: "Delete",
        hint: "Delete this item",
        execute: Remove,
        canExecute: item => AllowDelete && item != null,
        style: CommandStyle.Danger
    );

    /// <summary>
    /// Command to refresh the collection from the query.
    /// </summary>
    public CommandViewModel RefreshCommand => _refreshCommand ??= new CommandViewModel(
        parent: this,
        text: "Refresh",
        hint: "Reload the collection",
        execute: Refresh,
        style: CommandStyle.Info
    );

    #endregion

    #region CRUD Operations

    /// <summary>
    /// Adds a new item to the collection.
    /// </summary>
    public void Add()
    {
        if (!AllowAdd || CreateItem == null) return;

        var newItem = CreateItem();
        Collection.Add(newItem);
        OnItemAdded?.Invoke(newItem);
        SelectedItem = newItem;

        // Notify UI of collection change
        OnPropertyChanged(nameof(Collection));
        OnPropertyChanged(nameof(Count));
        OnPropertyChanged(nameof(ColumnFields));

        Validate();
    }

    /// <summary>
    /// Removes an item from the collection.
    /// </summary>
    public void Remove(T item)
    {
        if (!AllowDelete || item == null) return;

        OnItemDeleted?.Invoke(item);
        Collection.Remove(item);

        if (SelectedItem == item)
        {
            SelectedItem = Collection.FirstOrDefault();
        }

        // Notify UI of collection change
        OnPropertyChanged(nameof(Collection));
        OnPropertyChanged(nameof(Count));
        OnPropertyChanged(nameof(ColumnFields));

        Validate();
    }

    /// <summary>
    /// Refreshes the collection from the query.
    /// </summary>
    public void Refresh()
    {
        if (_query == null) return;

        if (_collection != null)
        {
            _collection.CollectionChanged -= OnCollectionChanged;
        }

        _collection = new ObservableCollection<T>(_query());
        _collection.CollectionChanged += OnCollectionChanged;
        _isInitialized = true;

        OnPropertyChanged(nameof(Collection));
        OnPropertyChanged(nameof(Count));
        OnPropertyChanged(nameof(ColumnFields));

        if (SelectedItem != null && !Collection.Contains(SelectedItem))
        {
            SelectedItem = Collection.FirstOrDefault();
        }

        Validate();
    }

    #endregion

    #region Validation

    /// <summary>
    /// FluentValidation rules for the collection.
    /// Example: Minimum/maximum item count.
    /// </summary>
    public Action<IRuleBuilder<CollectionFieldViewModel<T>, ObservableCollection<T>>>? ValidationRules { get; set; }

    /// <summary>
    /// Validates the collection (e.g., min/max count).
    /// </summary>
    public void Validate()
    {
        Error = null;
        Warning = null;

        if (ValidationRules == null) return;

        var validator = new InlineValidator<CollectionFieldViewModel<T>>();
        var ruleBuilder = validator.RuleFor(x => x.Collection);
        ValidationRules(ruleBuilder);

        var result = validator.Validate(this);

        var errors = result.Errors.Where(e => e.Severity == Severity.Error).ToList();
        var warnings = result.Errors.Where(e => e.Severity == Severity.Warning).ToList();

        if (errors.Any())
        {
            Error = errors.First().ErrorMessage;
        }
        else if (warnings.Any())
        {
            Warning = warnings.First().ErrorMessage;
        }
    }

    #endregion

    #region Private Helpers

    private void OnCollectionChanged(object? sender, NotifyCollectionChangedEventArgs e)
    {
        OnPropertyChanged(nameof(Count));
        OnPropertyChanged(nameof(ColumnFields));
    }

    #endregion

    public override string ToString()
    {
        return Label ?? $"Liste ({Label})";
    }
}
