namespace Model.ViewModels;

/// <summary>
/// Interface for collection-level FieldViewModels.
/// Manages collections of ViewModels with CRUD operations.
/// </summary>
public interface ICollectionFieldViewModel : IFieldViewModel
{
    /// <summary>
    /// Number of items in the collection.
    /// </summary>
    int Count { get; }

    /// <summary>
    /// Whether adding new items is allowed.
    /// </summary>
    bool AllowAdd { get; set; }

    /// <summary>
    /// Whether updating existing items is allowed.
    /// </summary>
    bool AllowUpdate { get; set; }

    /// <summary>
    /// Whether deleting items is allowed.
    /// </summary>
    bool AllowDelete { get; set; }

    /// <summary>
    /// List of IFieldViewModel properties visible as columns.
    /// Auto-generated by reflection on T.
    /// </summary>
    IReadOnlyList<IFieldViewModel> ColumnFields { get; }

    /// <summary>
    /// Refreshes the collection from the query.
    /// </summary>
    void Refresh();
}
